{% set name = "pymunk" %}
{% set version = "5.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 585aabe9a7039b7a2dc07217120b6ccfc2abc200bd381187e0912ae852a63894

build:
  number: 1
  # Note: --no-deps is currently required due to https://github.com/conda/conda-build/issues/3254
  # Once resolved, it should be removed.
  script:
    - export LDFLAGS="-dynamiclib $LDFLAGS"  # [osx]
    - export LD=$CC  # [osx]
    - export CFLAGS="$CFLAGS -O3"  # [linux]
    - export LDFLAGS="-shared $LDFLAGS"  # [linux]
    - export LD=$CC  # [linux]
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('c') }}  # [unix]
  host:
    - python
    - pip
    - cffi  # [python_impl != "pypy"]
  run:
    - python
    - cffi  # [python_impl != "pypy"]

test:
  commands:
    - python -m pymunk.tests UnitTest

about:
  home: https://www.pymunk.org
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Pymunk is a easy-to-use pythonic 2d physics library
  description: |
    Pymunk is a easy-to-use pythonic 2d physics library that can be used 
    whenever you need 2d rigid body physics from Python. Perfect when you need 
    2d physics in your game, demo or other application! It is built on top of 
    the very capable 2d physics library Chipmunk <http://chipmunk-physics.net>.
  doc_url: https://www.pymunk.org
  dev_url: https://github.com/viblo/pymunk

extra:
  recipe-maintainers:
    - viblo
