{% set name = "pymunk" %}
{% set version = "6.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 60dcd9ff0433e6ce49e5cb577a4368d0592c4685f4deb644d705c882161c724e

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cffi                                   # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cffi  # [python_impl != "pypy"]
  run:
    - python
    - cffi  # [python_impl != "pypy"]

test:
  commands:
    - python -m pymunk.tests

about:
  home: https://www.pymunk.org
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Pymunk is a easy-to-use pythonic 2d physics library
  description: |
    Pymunk is a easy-to-use pythonic 2d physics library that can be used 
    whenever you need 2d rigid body physics from Python. Perfect when you need 
    2d physics in your game, demo or other application! It is built on top of 
    the very capable 2d physics library Chipmunk <http://chipmunk-physics.net>.
  doc_url: https://www.pymunk.org
  dev_url: https://github.com/viblo/pymunk

extra:
  recipe-maintainers:
    - viblo
