{% set name = "pymunk" %}
{% set version = "6.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 765f7c561a859a1b565bc517a47cc3992d6258e860f9174c533033c218af63c3

build:
  number: 1
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cffi                                   # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - cffi  # [python_impl != "pypy"]
  run:
    - python
    - cffi  # [python_impl != "pypy"]

test:
  commands:
    - python -m pymunk.tests

about:
  home: https://www.pymunk.org
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Pymunk is a easy-to-use pythonic 2d physics library
  description: |
    Pymunk is a easy-to-use pythonic 2d physics library that can be used 
    whenever you need 2d rigid body physics from Python. Perfect when you need 
    2d physics in your game, demo or other application! It is built on top of 
    the very capable 2d physics library Chipmunk <http://chipmunk-physics.net>.
  doc_url: https://www.pymunk.org
  dev_url: https://github.com/viblo/pymunk

extra:
  recipe-maintainers:
    - viblo
