{% set name = "pymunk" %}
{% set version = "7.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 96a38e8123f4d89f8820b43640f1f623d6844f1f97eea09c4660f031780a9ff8

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cffi                                   # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - cffi  # [python_impl != "pypy"]
    - setuptools
  run:
    - python
    - cffi  # [python_impl != "pypy"]

test:
  commands:
    - python -m pymunk.tests

about:
  home: https://www.pymunk.org
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Pymunk is a easy-to-use pythonic 2d physics library
  description: |
    Pymunk is an easy-to-use pythonic 2D physics library that can be used 
    whenever you need 2D rigid body physics from Python. Perfect when you need 
    2D physics in your game, demo or simulation! It is built on top of Munk2D, 
    a fork of the very capable 2D physics library Chipmunk2D 
    <http://chipmunk-physics.net>.
  doc_url: https://www.pymunk.org
  dev_url: https://github.com/viblo/pymunk

extra:
  recipe-maintainers:
    - viblo
