# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "bIDSuvAvikXDTIkb5cEtgWoitDhuCGcl0abDmvehVgrof754Rb3HAxzq1tc7PaAfzbNUocH6o67nvrm/6wUnYzK70/yEaCwpgmKq7LQrP/15e4C1zOaOD+MzwWFV+Ky2r2qn+mJi70Ej67yAsLHYoeLwUptvD0bZ1ed26Zjr63r74ze+4D4TG/HWAkHVKCqltWYbPmotlyZuYA5Woxiq/qSgm7uOS2ajuofedfXClgnTauaMx4ugwpiPb5+NSd+PhA4TkNNoi0l2d/qbJSUIrZq9mstLBPw4MK436rguOdyEJpo7uf6hHAMVSBlcxFDxEBzK7PhsFshOEksk2UOguxwabyHqoPCLNQODQpi6/uIfl0a6fdbP63UherNwWGmcPz5Lo6isFvDFdfovibbx4s1Z6CxqawL4iCzOK9wc5O5QlzcNrrA6MoFJHRPWYybChmfKG0k7/aS2X4RDjuSsMZgyIKky/PWLR3VnzmrjTL57k+/3mtKN2fgqfU7HdmuMzVK6VF7ys1NFcqK+cMMqQnlJzYzZbw+2LvIRk/6uvdcSY1jRxvelKTI/F0YH5rYcahwtUcHkSK3jdlzRThXXeTTrbIa5609/wj8XLQVvj7ZD80+3dFPgdgcZTjCvGBpCrC6gQSpKYYjYphJUfr0FVOyNDIRXacIvcz8k8WzDMxQ="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml