travis:
  secure:
    BINSTAR_TOKEN: bIDSuvAvikXDTIkb5cEtgWoitDhuCGcl0abDmvehVgrof754Rb3HAxzq1tc7PaAfzbNUocH6o67nvrm/6wUnYzK70/yEaCwpgmKq7LQrP/15e4C1zOaOD+MzwWFV+Ky2r2qn+mJi70Ej67yAsLHYoeLwUptvD0bZ1ed26Zjr63r74ze+4D4TG/HWAkHVKCqltWYbPmotlyZuYA5Woxiq/qSgm7uOS2ajuofedfXClgnTauaMx4ugwpiPb5+NSd+PhA4TkNNoi0l2d/qbJSUIrZq9mstLBPw4MK436rguOdyEJpo7uf6hHAMVSBlcxFDxEBzK7PhsFshOEksk2UOguxwabyHqoPCLNQODQpi6/uIfl0a6fdbP63UherNwWGmcPz5Lo6isFvDFdfovibbx4s1Z6CxqawL4iCzOK9wc5O5QlzcNrrA6MoFJHRPWYybChmfKG0k7/aS2X4RDjuSsMZgyIKky/PWLR3VnzmrjTL57k+/3mtKN2fgqfU7HdmuMzVK6VF7ys1NFcqK+cMMqQnlJzYzZbw+2LvIRk/6uvdcSY1jRxvelKTI/F0YH5rYcahwtUcHkSK3jdlzRThXXeTTrbIa5609/wj8XLQVvj7ZD80+3dFPgdgcZTjCvGBpCrC6gQSpKYYjYphJUfr0FVOyNDIRXacIvcz8k8WzDMxQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
